In [112]:
import pandas as pd
from unidecode import unidecode

In [ ]:
df = pd.read_excel(r"data\Taco-4a-Edicao.xlsx")

In [114]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 597 entries, 0 to 596
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Número                 597 non-null    int64
 1   Grupo                  597 non-null    str
 2   Descrição do Alimento  597 non-null    str
 3   Energia(kcal)          595 non-null    object
 4   Energia(kJ)            595 non-null    object
 5   Proteína(g)            586 non-null    object
 6   Lipídeos(g)            594 non-null    object
 7   Colesterol(mg)         267 non-null    object
 8   Carboidrato(g)         586 non-null    object
 9   Fibra Alimentar(g)     370 non-null    object
 10  Cálcio(mg)             586 non-null    object
 11  Magnésio(mg)           586 non-null    object
 12  Manganês(mg)           586 non-null    object
 13  Fósforo(mg)            586 non-null    object
 14  Ferro(mg)              586 non-null    object
 15  Sódio(mg)              589 non-null    object
 16  Potássio(mg)           587 non-null    object
 17  Cobre(mg)              586 non-null    object
 18  Zinco(mg)              585 non-null    object
 19  VitaminaC(mg)          400 non-null    object
dtypes: int64(1), object(17), str(2)
memory usage: 93.4+ KB

In [115]:
df.head()

,Número,Grupo,Descrição do Alimento,Energia(kcal),Energia(kJ),Proteína(g),Lipídeos(g),Colesterol(mg),Carboidrato(g),Fibra Alimentar(g),Cálcio(mg),Magnésio(mg),Manganês(mg),Fósforo(mg),Ferro(mg),Sódio(mg),Potássio(mg),Cobre(mg),Zinco(mg),VitaminaC(mg)
0,1,Cereais e derivados,"Arroz, integral, cozido",123.534893,516.86999,2.58825,1.000333,NaN,25.80975,2.749333,5.204,58.702,0.627333,105.853,0.262,1.244667,75.151667,0.020333,0.682667,NaN
1,2,Cereais e derivados,"Arroz, integral, cru",359.678002,1504.892761,7.323286,1.864833,NaN,77.450714,4.819167,7.818,109.71,2.993333,250.865,0.948333,1.645667,173.34,0.074833,1.395167,NaN
2,3,Cereais e derivados,"Arroz, tipo 1, cozido",128.258486,536.633504,2.520817,0.227,NaN,28.05985,1.561,3.544333,2.253333,0.296667,17.945,0.076667,1.200667,14.673667,0.015,0.491333,NaN
3,4,Cereais e derivados,"Arroz, tipo 1, cru",357.789273,1496.990319,7.15854,0.335,NaN,78.759543,1.639167,4.414333,30.383667,1.032333,104.207583,0.677747,1.019167,62.499417,0.114833,1.224833,NaN
4,5,Cereais e derivados,"Arroz, tipo 2, cozido",130.119648,544.420609,2.568417,0.361667,NaN,28.192583,1.069667,3.333667,6.053333,0.371,21.521333,0.050333,1.959667,20.203333,0.041,0.549333,NaN

TRATAMENTO

In [116]:
df_clean = df[["Número","Grupo","Descrição do Alimento","Energia(kcal)", 'Energia(kJ)', "Proteína(g)", "Carboidrato(g)", "Lipídeos(g)",'Fibra Alimentar(g)']]

In [117]:
df_clean = df_clean.rename(columns={'Número': 'id'})
df_clean.columns = [unidecode(col).lower() for col in df_clean.columns]

In [118]:
# aqui eu tentei dar uma comprimida nos tipos de variedade, eu quebro a descrição do alimento assim: 
# exemplo: arroz, integral, cozido → → → base = arroz | tipo = integral
# mantém 1 linha para cada combinação de (base + tipo) funcionou mais ou menos rsrs
def delete_rep(desc):
    partes = [p.strip().lower() for p in desc.split(",")]
    
    base = partes[0] if len(partes) > 0 else None
    tipo = partes[1] if len(partes) > 1 else None
    
    return pd.Series([base, tipo])

df_clean[["base", "tipo"]] = df_clean["descricao do alimento"].apply(delete_rep)

df_clean = df_clean.drop_duplicates(subset=["base", "tipo"])
df_clean = df_clean.drop(columns=["base", "tipo"])

In [120]:
colunas = [
    "energia(kcal)", "energia(kj)", "proteina(g)",
    "carboidrato(g)", "lipideos(g)", "fibra alimentar(g)"]

df_clean[colunas] = df_clean[colunas].apply(pd.to_numeric, errors="coerce")

df_clean = df_clean.round(1)

In [121]:
sorted(df_clean["grupo"].unique())

['Alimentos preparados',
 'Bebidas (alcoólicas e não alcoólicas)',
 'Carnes e derivados',
 'Cereais e derivados',
 'Frutas e derivados',
 'Gorduras e óleos',
 'Leguminosas e derivados',
 'Leite e derivados',
 'Miscelâneas',
 'Outros alimentos industrializados',
 'Ovos e derivados',
 'Pescados e frutos do mar',
 'Produtos açucarados',
 'Verduras, hortaliças e derivados']

In [122]:
df_clean = df_clean[~df_clean["grupo"].isin([
    "Alimentos preparados",
    "Bebidas (alcoólicas e não alcoólicas)",
    "Miscelâneas"
])]

In [123]:
df_clean.info()

<class 'pandas.DataFrame'>
Index: 376 entries, 0 to 596
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     376 non-null    int64
 1   grupo                  376 non-null    str
 2   descricao do alimento  376 non-null    str
 3   energia(kcal)          374 non-null    float64
 4   energia(kj)            374 non-null    float64
 5   proteina(g)            363 non-null    float64
 6   carboidrato(g)         366 non-null    float64
 7   lipideos(g)            350 non-null    float64
 8   fibra alimentar(g)     272 non-null    float64
dtypes: float64(6), int64(1), str(2)
memory usage: 29.4 KB

In [124]:
df_clean.head(50)

,id,grupo,descricao do alimento,energia(kcal),energia(kj),proteina(g),carboidrato(g),lipideos(g),fibra alimentar(g)
0,1,Cereais e derivados,"Arroz, integral, cozido",123.5,516.9,2.6,25.8,1.0,2.7
2,3,Cereais e derivados,"Arroz, tipo 1, cozido",128.3,536.6,2.5,28.1,0.2,1.6
4,5,Cereais e derivados,"Arroz, tipo 2, cozido",130.1,544.4,2.6,28.2,0.4,1.1
6,7,Cereais e derivados,"Aveia, flocos, crua",393.8,1647.8,13.9,66.6,8.5,9.1
7,8,Cereais e derivados,"Biscoito, doce, maisena",442.8,1852.8,8.1,75.2,12.0,2.1
12,13,Cereais e derivados,"Biscoito, salgado, cream cracker",431.7,1806.4,10.1,68.7,14.4,2.5
13,14,Cereais e derivados,"Bolo, mistura para",418.6,1751.6,6.2,84.7,6.1,1.7
14,15,Cereais e derivados,"Bolo, pronto, aipim",323.9,1355.0,4.4,47.9,12.7,0.7
18,19,Cereais e derivados,"Canjica, branca, crua",357.6,1496.2,7.2,78.1,1.0,5.5
19,20,Cereais e derivados,"Canjica, com leite integral",112.5,470.5,2.4,23.6,1.2,1.2
20,21,Cereais e derivados,"Cereais, milho, flocos, com sal",369.6,1546.4,7.3,80.8,1.6,5.3
22,23,Cereais e derivados,"Cereais, mingau, milho, infantil",394.4,1650.3,6.4,87.3,1.1,3.2
23,24,Cereais e derivados,"Cereais, mistura para vitamina, trigo, cevada ...",381.1,1594.7,8.9,81.6,2.1,5.0
24,25,Cereais e derivados,"Cereal matinal, milho",365.4,1528.6,7.2,83.8,1.0,4.1
26,27,Cereais e derivados,"Creme de arroz, pó",386.0,1615.0,7.0,83.9,1.2,1.1
27,28,Cereais e derivados,"Creme de milho, pó",333.0,1393.4,4.8,86.1,1.6,3.7
28,29,Cereais e derivados,"Curau, milho verde",78.4,328.2,2.4,13.9,1.6,0.5
30,31,Cereais e derivados,"Farinha, de arroz, enriquecida",363.1,1519.0,1.3,85.5,0.3,0.6
31,32,Cereais e derivados,"Farinha, de centeio, integral",335.8,1404.9,12.5,73.3,1.8,15.5
32,33,Cereais e derivados,"Farinha, de milho, amarela",350.6,1466.9,7.2,79.1,1.5,5.5
33,34,Cereais e derivados,"Farinha, de rosca",370.6,1550.5,11.4,75.8,1.5,4.8
34,35,Cereais e derivados,"Farinha, de trigo",360.5,1508.2,9.8,75.1,1.4,2.3
35,36,Cereais e derivados,"Farinha, láctea, de cereais",414.9,1735.7,11.9,77.8,5.8,1.9
36,37,Cereais e derivados,"Lasanha, massa fresca, cozida",163.8,685.2,5.8,32.5,1.2,1.6
38,39,Cereais e derivados,"Macarrão, instantâneo",435.9,1823.7,8.8,62.4,17.2,5.6
39,40,Cereais e derivados,"Macarrão, trigo, cru",371.1,1552.8,10.0,77.9,1.3,2.9
41,42,Cereais e derivados,"Milho, amido, cru",361.4,1512.0,0.6,87.1,NaN,0.7
42,43,Cereais e derivados,"Milho, fubá, cru",353.5,1479.0,7.2,78.9,1.9,4.7
43,44,Cereais e derivados,"Milho, verde, cru",138.2,578.1,6.6,28.6,0.6,3.9
45,46,Cereais e derivados,"Mingau tradicional, pó",373.4,1562.4,0.6,89.3,0.4,0.9
46,47,Cereais e derivados,"Pamonha, barra para cozimento, pré-cozida",171.2,716.4,2.6,30.7,4.8,2.4
47,48,Cereais e derivados,"Pão, aveia, forma",343.1,1435.5,12.4,59.6,5.7,6.0
48,49,Cereais e derivados,"Pão, de soja",308.7,1291.7,11.3,56.5,3.6,5.7
49,50,Cereais e derivados,"Pão, glúten, forma",253.0,1058.5,12.0,44.1,2.7,2.5
50,51,Cereais e derivados,"Pão, milho, forma",292.0,1221.8,8.3,56.4,3.1,4.3
51,52,Cereais e derivados,"Pão, trigo, forma, integral",253.2,1059.4,9.4,49.9,3.7,6.9
54,55,Cereais e derivados,"Pastel, de carne, cru",288.7,1207.9,10.7,42.0,8.8,1.0
56,57,Cereais e derivados,"Pastel, de queijo, cru",308.5,1290.7,9.9,45.9,9.6,1.1
58,59,Cereais e derivados,"Pastel, massa, crua",310.2,1297.9,6.9,57.4,5.5,1.4
60,61,Cereais e derivados,"Pipoca, com óleo de soja, sem sal",448.3,1875.8,9.9,70.3,15.9,14.3
61,62,Cereais e derivados,"Polenta, pré-cozida",102.7,429.9,2.3,23.3,0.3,2.4
62,63,Cereais e derivados,"Torrada, pão francês",377.4,1579.1,10.5,74.6,3.3,3.4
63,64,"Verduras, hortaliças e derivados","Abóbora, cabotian, cozida",48.0,201.0,1.4,10.8,0.7,2.5
65,66,"Verduras, hortaliças e derivados","Abóbora, menina brasileira, crua",13.6,56.9,0.6,3.3,NaN,1.2
66,67,"Verduras, hortaliças e derivados","Abóbora, moranga, crua",12.4,51.7,1.0,2.7,0.1,1.7
68,69,"Verduras, hortaliças e derivados","Abóbora, pescoço, crua",24.5,102.4,0.7,6.1,0.1,2.3
69,70,"Verduras, hortaliças e derivados","Abobrinha, italiana, cozida",15.0,62.9,1.1,3.0,0.2,1.6
72,73,"Verduras, hortaliças e derivados","Abobrinha, paulista, crua",30.8,128.9,0.6,7.9,0.1,2.6
73,74,"Verduras, hortaliças e derivados","Acelga, crua",20.9,87.6,1.4,4.6,0.1,1.1
74,75,"Verduras, hortaliças e derivados","Agrião, cru",16.6,69.4,2.7,2.3,0.2,2.1

In [ ]:
df_clean.to_excel("taco_reduzido.xlsx", index=False)

# ------------------------------------------------------------
# Nota:
# Foram realizados outros processos de limpeza e redução
# do dataset de forma manual, fora deste script.
# ------------------------------------------------------------